[build]
    command ="gatsby build"
    publish ="public"
    functions="functions"

[[redirects]]
    from = "/lolly/*"
    to = "/.netlify/functions/showLolly?id=:splat"
    status = 302

[[redirects]]
    from = "/*"
    to = "/404"
    status = 404