[build]
    command ="gatsby build"
    publish ="public"
    functions="functions"


[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/showLolly?id=:splat"
  status = 200

[[redirects]]
    from = "/*"
    to = "/404"
    status = 404